### ISSUE TITLE
Playing audio and loadItem() has a few seconds delay

### ISSUE THREAD

**Issue by Blogshot** [sedmelluq/lavaplayer#11] opened 2017-01-16 22:38 UTC
I have a folder full of small mp3-files (1 to 5 seconds). They are freshly encoded and without errors. I am using v1.1.41.
Every few invokations the audio takes a few seconds to be played. Additionally, following exception is thrown nearly every time a file is played:
```
22:45:05.664 [Voice Send Handler] ERROR sx.blah.discord.Discord4J - Encountered error on voice websocket:
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:936)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.flush(FrameFlusher.java:153)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher$Flusher.process(FrameFlusher.java:217)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:382)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:614)
	at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame(WebSocketClientConnection.java:72)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:289)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:283)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:123)
	at sx.blah.discord.api.internal.DiscordVoiceWS.disconnect(DiscordVoiceWS.java:137)
	at sx.blah.discord.handle.impl.obj.VoiceChannel.leave(VoiceChannel.java:119)
	at main.Main.leaveVoiceChannel(Main.java:110)
	at main.Main.handleTrackFinished(Main.java:298)
	at util.TrackScheduler.onTrackEnd(LavaPlayer.java:119)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:282)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:211)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:188)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:160)
	at util.AudioProvider.isReady(LavaPlayer.java:175)
	at sx.blah.discord.handle.audio.impl.DefaultProcessor.isReady(DefaultProcessor.java:21)
	at sx.blah.discord.handle.audio.impl.AudioManager.getAudioDataForProvider(AudioManager.java:87)
	at sx.blah.discord.handle.audio.impl.AudioManager.getAudio(AudioManager.java:78)
	at sx.blah.discord.api.internal.DiscordVoiceWS$1.run(DiscordVoiceWS.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:478)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
	... 36 common frames omitted
```

My code is loosely based on the Discord4J-Demo. I marked in my code where the delays are produced.
```
public class LavaPlayer {
  private final AudioPlayerManager playerManager;
  private final Map<Long, GuildMusicManager> musicManagers;
  
  public LavaPlayer() {
    this.musicManagers = new HashMap<>();
    
    this.playerManager = new DefaultAudioPlayerManager();
    AudioSourceManagers.registerRemoteSources(playerManager);
    AudioSourceManagers.registerLocalSource(playerManager);
  }
  
  private synchronized GuildMusicManager getGuildAudioPlayer(IGuild guild) {
    long guildId = Long.parseLong(guild.getID());
    GuildMusicManager musicManager = musicManagers.get(guildId);
    
    if (musicManager == null) {
      musicManager = new GuildMusicManager(playerManager, guild);
      musicManagers.put(guildId, musicManager);
    }
    
    guild.getAudioManager().setAudioProvider(musicManager.getAudioProvider());
    
    return musicManager;
  }
  
  public void playAudio(IVoiceChannel voiceChannel, IChannel textChannel, URL soundFile, IUser user) {
    
    GuildMusicManager musicManager = getGuildAudioPlayer(textChannel.getGuild());
    
    playerManager.loadItem(soundFile.getPath(), new AudioLoadResultHandler() {
      @Override
      public void trackLoaded(AudioTrack track) {

// sometimes bot takes a few seconds to join channel
        voiceChannel.join();

// sometimes bot takes a few seconds to play audio after joining
        musicManager.player.playTrack(track);
      }
      
      @Override
      public void playlistLoaded(AudioPlaylist playlist) {}
      
      @Override
      public void noMatches() {}
      
      @Override
      public void loadFailed(FriendlyException exception) {
        Main.getInstance().writeMessage(textChannel, "Could not play: " + exception.getMessage());
      }
    });
  }
}

class GuildMusicManager {
  public final AudioPlayer player;
  
  public GuildMusicManager(AudioPlayerManager manager, IGuild guild) {
    player = manager.createPlayer();

    player.addListener(new AudioEventAdapter() {
      @Override
      public void onTrackEnd(AudioPlayer player, AudioTrack track, AudioTrackEndReason endReason) {
        Main.getInstance().handleTrackFinished(guild);
      }
    });
  }
  
  public AudioProvider getAudioProvider() {
    return new AudioProvider(player);
  }
}

class AudioProvider implements IAudioProvider {
  private final AudioPlayer audioPlayer;
  private AudioFrame lastFrame;
  
  public AudioProvider(AudioPlayer audioPlayer) {
    this.audioPlayer = audioPlayer;
  }
  
  @Override
  public boolean isReady() {
    if (lastFrame == null) {
      lastFrame = audioPlayer.provide();
    }
    
    return lastFrame != null;
  }
  
  @Override
  public byte[] provide() {
    if (lastFrame == null) {
      lastFrame = audioPlayer.provide();
    }
    
    byte[] data = lastFrame != null ? lastFrame.data : null;
    lastFrame = null;
    
    return data;
  }
  
  @Override
  public int getChannels() {
    return 2;
  }
  
  @Override
  public AudioEncodingType getAudioEncodingType() {
    return AudioEncodingType.OPUS;
  }
}
```

I don't know where to go from here. 

Additional info: The bot ist hosted on a 2GHz, 2GB RAM machine with 100 MBit/s upload. There are roughly 1600 connected guilds, the bot is invoked every few seconds.

**Comment by sedmelluq** [comment] 2017-01-19 15:21
Seems to be an issue with joining a voice channel. If this does not reproduce with an already open voice connection, then it isn't related to LavaPlayer.

**Comment by sedmelluq** [comment] 2017-02-17 23:31
Been open for a month and no feedback. Closing.

**Closed by sedmelluq** 2017-02-17 23:31 UTC
