### ISSUE TITLE
YouTube not work

### ISSUE THREAD

**Issue by superSebi** [sedmelluq/lavaplayer#192] opened 2019-07-17 19:43 UTC
YouTube video doesn`t work...

[lava-daemon-pool-playback-1-thread-34] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of 3EGeVbpNG3A
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:149)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:165)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 more

**Comment by Shadorc** [comment] 2019-07-17 20:16
Are you using version 1.3.17 ?

**Comment by Seblofs** [comment] 2019-07-17 20:30
I think so, in the maven Import stands by the version "LATEST" so it must be the latest version, or not?

**Comment by Shadorc** [comment] 2019-07-17 21:21
1.3.17 os the latest version on Maven, yes. However, this is a duplicate of https://github.com/sedmelluq/lavaplayer/issues/188

**Comment by Seblofs** [comment] 2019-07-17 21:32
And this post is bringing me back to my Post. What can i do now?

**Comment by Shadorc** [comment] 2019-07-17 22:09
If the bug is confirmed on 1.3.17, there is no fix right now, sorry :/

**Comment by MCOfficer** [comment] 2019-07-18 06:44
in the meantime, don't use LATEST, it has been deprecated for years.

**Comment by Seblofs** [comment] 2019-07-18 11:41
> in the meantime, don't use LATEST, it has been deprecated for years (also, [dynamic versions are bad](https://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/)). As far as i know, it doesn't even make guarantees that it's truly the latest versions.

Ok, now i have 1.3.17 into the Versions tag.
But it still does not work...

**Comment by sedmelluq** [comment] 2020-11-06 05:36
Fixed.

**Closed by sedmelluq** 2020-11-06 05:36 UTC
