### ISSUE TITLE
Error YT playback

### ISSUE THREAD

**Issue by TairyHesticl** [sedmelluq/lavaplayer#87] opened 2018-02-09 17:57 UTC
Hello,

recently i´ve been getting this error for most of the yt links i am trying to playback.
Any ideas on what could be causing this?

2018-02-09 15:30:55.405 INFO 7380 --- [inWS-ReadThread] n.d.d.listeners.ChatSou
ndBoardListener : net.dv8tion.jda.core.events.message.MessageEmbedEvent@6d8caa
90
2018-02-09 15:30:55.849 ERROR 7380 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioT
rackExecutor : Error in playback of PEGccV-NOm8

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when p
laying the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyE
xceptions(ExceptionTools.java:40) ~[classes!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecut
or.execute(LocalAudioTrackExecutor.java:102) ~[classes!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lam
bda$executeTrack$1(DefaultAudioPlayerManager.java:348) [classes!/:2.2.0-beta]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[n
a:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[
na:1.8.0_161]
at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]
Caused by: java.lang.IllegalStateException: Must find action functions from scri
pt.
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:164) ~[class
es!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:129) ~[classe
s!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.getValidUrl(YoutubeSignatureCipherManager.java:88) ~[classes!/:2.2.0-be
ta]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loa
dBestFormatWithUrl(YoutubeAudioTrack.java:99) ~[classes!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.pro
cess(YoutubeAudioTrack.java:60) ~[classes!/:2.2.0-beta]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecut
or.execute(LocalAudioTrackExecutor.java:90) ~[classes!/:2.2.0-beta]
... 4 common frames omitted

**and this one here:**

2018-02-09 18:32:48.811 ERROR 7904 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioT
rackExecutor      : Error in playback of COKg-MttlvI

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when p
laying the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyE
xceptions(ExceptionTools.java:40) ~[classes!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecut
or.execute(LocalAudioTrackExecutor.java:102) ~[classes!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lam
bda$executeTrack$1(DefaultAudioPlayerManager.java:348) [classes!/:2.2.0-beta]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[n
a:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[
na:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_161]
Caused by: java.lang.IllegalStateException: Must find action functions from scri
pt.
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:164) ~[class
es!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:129) ~[classe
s!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCiphe
rManager.getValidUrl(YoutubeSignatureCipherManager.java:88) ~[classes!/:2.2.0-be
ta]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loa
dBestFormatWithUrl(YoutubeAudioTrack.java:99) ~[classes!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.pro
cess(YoutubeAudioTrack.java:60) ~[classes!/:2.2.0-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecut
or.execute(LocalAudioTrackExecutor.java:90) ~[classes!/:2.2.0-beta]
        ... 4 common frames omitted

**Comment by Frederikam** [comment] 2018-02-09 19:48
Duplicate of https://github.com/sedmelluq/lavaplayer/issues/85

**Closed** 2018-02-10 13:09 UTC
