### ISSUE TITLE
Audio lagging / Skipping issues

### ISSUE THREAD

**Issue by krwachir** [sedmelluq/lavaplayer#28] opened 2017-04-03 10:21 UTC
I really love this lib as it's light yet powerful. But my bot experiencing some issues with playback rate, sometimes the song got jumpy, faster/slower. Is this mainly because of the ping to discord server? My machine is 2 Cores with 2GB mem. Please address how I would fix it.

**Comment by Frederikam** [comment] 2017-04-03 10:23
Be sure to check that your CPU, RAM and network aren't choking. Also check the log.

**Comment by Repulser** [comment] 2017-04-03 10:28
Could also be a matter of where your server is located, from my experience Amsterdam / Paris works badly, and US servers work best.

**Comment by krwachir** [comment] 2017-04-04 03:43
My server is in Thailand and the discord voice server I choose is Singapore which is relatively close. Memory usage is quite low so I dont know what cause the issue

**Comment by R3alCl0ud** [comment] 2017-04-06 19:11
@krwachir This is an issue caused by latency to discord's voice servers, and is most likely cause by high latency on your client, not the bot's server.

**Comment by Frederikam** [comment] 2017-04-06 19:18
> This is an issue caused by latency to discord's voice servers, and is most likely cause by high latency on your client, not the bot's server.

This is difficult to know for certain if you are not monitoring the bot's audio output. Maybe it is outputting null frames (buffering issues), or just not sending enough frames (50 per second) due to slow transmission.

**Comment by krwachir** [comment] 2017-04-07 02:05
All,
I'm certain that everyone in the voice channel hear issues. For more info, I'm writing a bot using Discord4J. Initially, I used JDA-Player the audio might had some missing but no skipping or fast/slow playbacks.

What I noticed is that the ping is not really constant (also for all users) with discord, my client is showing around 40ms - 70ms. On machine resources, there was no cpu or memory spikes, the network bandwidth on server side has more than enough.

I'm not that good with audio and resampling but if you guys need anything else please let me know

**Comment by BroManDudeGuyPhD** [comment] 2017-07-09 07:50
@krwachir How many servers is your bot on? Mine is on about 9,100. Wonder if this is a large server bot issues or a general issue.

**Comment by sedmelluq** [comment] 2018-02-14 12:49
If you are still having issues, you can try to count how many `null` frames the `AudioPlayer` gives after the first few seconds of playing a new track. If there are `null` frames, then it may be a lavaplayer issue, otherwise it definitely is not.

**Comment by sedmelluq** [comment] 2018-03-19 17:04
Closing until any detailed report appears.

**Closed by sedmelluq** 2018-03-19 17:04 UTC
