### ISSUE TITLE
Received non-success response code 404, but video exists

### ISSUE THREAD

**Issue by cloudrac3r** [sedmelluq/lavaplayer#282] opened 2020-03-19 05:30 UTC
I'm using Lavalink.

I keep getting errors like these:
```
2020-03-19 06:17:21.730 ERROR 8701 --- [k-13-thread-176] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of SjXUKSbLnIQ

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.34.jar!/:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
 at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.io.IOException: Received non-success response code 404
 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.34.jar!/:na]
 at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.34.jar!/:na]
 ... 4 common frames omitted
```
However, the video with ID `SjXUKSbLnIQ` exists, and plays if I do the same thing again. Identical errors have previously occurred with IDs `8EJ3zbKTWQ8`, `7bnOLew0_M0`, `SkTt9k4Y-a8`, and more.

Seems like it's related to signature extraction? May or may not be relevant: https://github.com/ytdl-org/youtube-dl/commit/bf1317d / https://github.com/fent/node-ytdl-core/issues/486 / https://github.com/omarroth/invidious/issues/747

Let me know if I need to set a log level that prints more stuff.

**Comment by duncte123** [comment] 2020-03-19 07:37
The only one that doesn't play for me is `8EJ3zbKTWQ8` using lavaplayer `1.3.34`

**Comment by cloudrac3r** [comment] 2020-03-19 12:28
I can reproduce this error 3/3 times in both the Untied States and Singapore with ID `0uIYX4hbFBQ`.

**Comment by duncte123** [comment] 2020-03-19 20:28
Just received my first one https://sentry.io/share/issue/dbc7992f23d848008a8a673fc3936bd6/

It could be that YouTube is removing pbj or returning 404s instead of banning now

**Comment by cloudrac3r** [comment] 2020-03-20 14:48
It's not a ban — I'm able to load other items, and sometimes even the same item, correctly if I try again straight away. I suspect that the signature extractor function is simply not getting the correct URL, and so the URL that it does try is a 404.

**Comment by aikaterna** [comment] 2020-03-23 21:51
1.3.38 seems to resolve this, fwiw.

**Comment by Adi3000** [comment] 2020-04-10 14:27
Can reproduce the issues here with implementation on JMusicBot (https://github.com/jagrosh/MusicBot).
`eR99ubyBCGE` works from my home, but not from my OVH server.
Thoses time are perfect to be able to debug, test or open debugger remote to double check
Mainwhile, I've tested with `-Dhttp.proxy` and `-Dhttps.proxy` with differents server, seems to be the same...

**Comment by duncte123** [comment] 2020-04-10 14:44
> Can reproduce the issues here with implementation on JMusicBot (https://github.com/jagrosh/MusicBot).
> `eR99ubyBCGE` works from my home, but not from my OVH server.
> Thoses time are perfect to be able to debug, test or open debugger remote to double check
> Mainwhile, I've tested with `-Dhttp.proxy` and `-Dhttps.proxy` with differents server, seems to be the same...

What lavaplayer version is that on? The latest is `1.3.46` and I don't get 404's on that one

**Comment by MCOfficer** [comment] 2020-04-10 16:05
> What lavaplayer version is that on? 

1.3.46 but only since 20 hours on master - used to be 1.3.38 before that.

**Comment by Adi3000** [comment] 2020-04-10 17:09
> > What lavaplayer version is that on?
> 
> 1.3.46 but only since 20 hours on master - used to be 1.3.38 before that.

Ah, that why, my local is on the snapshot :) sorry for the trouble, I'll recompile and retry this :)

**Comment by Adi3000** [comment] 2020-04-10 17:17
Working perfectly on 1.3.46 I confirm ^^

**Comment by gravit0** [comment] 2020-04-10 20:55
Lastest 1.3.46, not work

**Comment by Adi3000** [comment] 2020-04-10 22:45
I've only tested loading `/watch?v=eR99ubyBCGE`, fwiw, it was not working on 1.3.38 but now this kind of link is working. Don't mind the case in which I mention working on my home or my server : I wasn't in the same version when I tested

**Comment by sedmelluq** [comment] 2020-11-06 04:47
The original issue (wrong domain for resolving player scripts) is fixed.

**Closed by sedmelluq** 2020-11-06 04:47 UTC
