### ISSUE TITLE
Livestream ends randomly

### ISSUE THREAD

**Issue by SoulSen** [sedmelluq/lavaplayer#144] opened 2018-11-15 01:11 UTC
I am using lavalink.py for my Discord bot, and I play a livestream 3-5 minutes in the livestream it suddenly ends without any errors or traceback. I wen't on lavalink.py's Discord and asked if it was the problem for lavalink or the wrapper, but they directed me to lavaplayer. Though this may be hard to identify as it gives no error. 

The livestream is: https://www.youtube.com/watch?v=hHW1oY26kxQ

**Comment by MCOfficer** [comment] 2018-11-15 03:05
might be related to #112

**Comment by SoulSen** [comment] 2018-11-15 05:43
> might be related to #112

Cannot clarify, as no error is given to console

**Comment by sedmelluq** [comment] 2019-03-20 17:49
Will close this as it is a duplicate of #112 .

**Closed by sedmelluq** 2019-03-20 17:49 UTC
