### ISSUE TITLE
Segmentation fault with latest lavaplayer version

### ISSUE THREAD

**Issue by cedrickring** [sedmelluq/lavaplayer#177] opened 2019-06-08 13:30 UTC
I'm getting a SIGSEGV when loading a Youtube URL. 

```
08.06.2019 13:26:18 INFO  c.s.l.c.natives.NativeLibraryLoader - Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$101/250890607@7b053a61
08.06.2019 13:26:18 INFO  c.s.l.c.natives.NativeLibraryLoader - Native library connector: loading with filter null
08.06.2019 13:26:18 INFO  c.s.l.c.natives.NativeLibraryLoader - Native library connector: successfully loaded.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000072b6, pid=1, tid=0x00007fc226b76b10
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
# Problematic frame:
# C  0x00000000000072b6
#
# Core dump written. Default location: /home/core or core.1
#
# An error report file with more information is saved as:
# /home/hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```

The Discord bot is running in a Docker container with the following Java base image: `openjdk:8-jre-alpine`

**Comment by napstr** [comment] 2019-06-08 18:04
Don't use alpine.

**Comment by cedrickring** [comment] 2019-06-08 18:07
But non-alpine images are huge af.

**Comment by 1Conan** [comment] 2019-07-04 07:11
Same thing here. Looks like it's a musl thing as adoptopenjdk alpine images that use glibc works properly.
I get the same error when I set a custom volume though.

**Comment by sedmelluq** [comment] 2020-11-06 05:39
Duplicate of #537

**Closed by sedmelluq** 2020-11-06 05:39 UTC
