### ISSUE TITLE
Player stops while playing a YouTube livestream

### ISSUE THREAD

**Issue by PT400C** [sedmelluq/lavaplayer#33] opened 2017-04-22 13:53 UTC
Hey,

I always get a strange issue, if I play a YouTube livestream with the lavaplayer. The stream works for 1 - 3 hours, after that the bot stops playing and throws an exception. Sometimes it is this:

[issue 1](https://pastebin.com/NAXe2PLR)

But even sometimes it is this:

[issue 2](https://pastebin.com/BdgEUxCa)

Everything else (Non-youtubelivestream) seems to be working. (Twitch, Soundcloud etc.)

**Comment by shikhir-arora** [comment] 2017-04-25 13:31
What version of lavaplayer? `1.2.36` adds video+AAC support which may fix the issue.

**Comment by PT400C** [comment] 2017-04-25 14:33
It is the latest version. 1.2.36.

**Comment by kcinnad** [comment] 2017-04-26 23:19
For me, the first song I start after I reboot my bot plays perfectly,
Then the next songs(I used the same for testing) will stop randomly

**Comment by ultimate255** [comment] 2017-05-23 11:32
On the latest 1.2.39
Same issue here, playing a live stream stops occasionally.. Anywhere from a few minutes of playing to a few hours.
The onTrackEnd event does trigger, no errors.

**Comment by Daniele122898** [comment] 2017-09-06 21:07
it used to work for me but now with the new YT design and stuff it stopped working. The livestream plays for like 10 seconds and then stops. no matter which livestream

**Comment by sedmelluq** [comment] 2021-03-29 12:12
Duplicate of https://github.com/sedmelluq/lavaplayer/issues/33

**Closed by sedmelluq** 2021-03-29 12:12 UTC
Labels: duplicate
