### ISSUE TITLE
lavaplayer does not include DaemonThreadFactory.class

### ISSUE THREAD

**Issue by mkoijn3** [sedmelluq/lavaplayer#124] opened 2018-07-10 21:39 UTC
I'm trying to make a Discord bot with JDA that uses lavaplayer but I keep getting a java.lang.NoClassDefFoundError, with the error message saying that it can't find com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory. I did a little digging in the .jar and found out that DaemonThreadFactory.class wasn't in it despite being a seemingly vital part of lavaplayer.

`java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:105)
	at test.bot.TestBot.onMessageReceived(TestBot.java:46)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:417)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more`

**Comment by napstr** [comment] 2018-07-10 22:02
Looks like a duplicate of #120

**Comment by mkoijn3** [comment] 2018-07-10 22:33
Well at least on this one I've identified the problem

**Comment by CodeBasePW** [comment] 2018-11-04 22:12
I don't know if this is useful information, but I actually went through a lot of the versions they have on bintray and decompiled each of them. First of all, the class that is throwing the exception doesn't decompile, and not even the earliest version listed (1.1.36) has a DaemonThreadFactory class. I'm working on a bot with a friend and we can't seem to figure out why this is an issue. All I know is that as of https://github.com/sedmelluq/lavaplayer/commit/facc8ebf3fa0d80896827e07b79303022988acc6 DefaultAudioPlayerManager.java clearly still has a reference to DaemonThreadFactory in it's constructor despite it not existing.

**Comment by sedmelluq** [comment] 2019-01-30 17:22
This class is in `lavaplayer-common` dependency.

**Closed** 2019-03-20 17:47 UTC
